#!/usr/bin/env python3
"""Production build pipeline for HostStorageService (ScreenAssist).

Runs a full clean build with PyInstaller (onedir) and packages the result
into a per-user Inno Setup installer.

Usage:
    python build_pipeline.py
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parent
APP_NAME = "HostStorageService"
MAIN_SCRIPT = ROOT_DIR / "main.py"
INSTALLER_SCRIPT = ROOT_DIR / "installer_config.iss"
INSTALLER_BASENAME = "HostStorageService_Setup"

PYINSTALLER_ARGS = [
    sys.executable,
    "-m",
    "PyInstaller",
    "--noconsole",
    "--onedir",
    "--clean",
    f"--name={APP_NAME}",
    str(MAIN_SCRIPT),
]

ISCC_CANDIDATES = (
    Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"),
    Path(r"C:\Program Files\Inno Setup 6\ISCC.exe"),
)

# Stable AppId — keep constant so Inno Setup upgrades in-place.
INNO_APP_ID = "{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}"

LOGGER = logging.getLogger("build_pipeline")


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------


def configure_logging() -> None:
    """Configure structured console logging for the pipeline."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%H:%M:%S",
    )


# ---------------------------------------------------------------------------
# Step 1 — Clean old artifacts
# ---------------------------------------------------------------------------


def clean_old_artifacts() -> None:
    """Remove previous build outputs so each run starts from a clean slate."""
    LOGGER.info("Step 1/5 — Cleaning old build artifacts")

    targets: list[Path] = [
        ROOT_DIR / "build",
        ROOT_DIR / "dist",
    ]
    targets.extend(ROOT_DIR.glob("*.spec"))

    for target in targets:
        if not target.exists():
            LOGGER.debug("Nothing to remove: %s", target)
            continue

        if target.is_dir():
            LOGGER.info("Removing directory: %s", target)
            shutil.rmtree(target)
        else:
            LOGGER.info("Removing file: %s", target)
            target.unlink()

    LOGGER.info("Cleanup complete")


# ---------------------------------------------------------------------------
# Step 2 — PyInstaller
# ---------------------------------------------------------------------------


def run_pyinstaller() -> None:
    """Build the application directory bundle with PyInstaller."""
    LOGGER.info("Step 2/5 — Running PyInstaller (onedir, noconsole)")
    LOGGER.info("Command: %s", " ".join(PYINSTALLER_ARGS))

    if not MAIN_SCRIPT.is_file():
        raise FileNotFoundError(f"Entry point not found: {MAIN_SCRIPT}")

    return_code = _stream_subprocess(PYINSTALLER_ARGS, cwd=ROOT_DIR)
    if return_code != 0:
        raise RuntimeError(f"PyInstaller failed with exit code {return_code}")

    bundle_dir = ROOT_DIR / "dist" / APP_NAME
    executable = bundle_dir / f"{APP_NAME}.exe"

    if not executable.is_file():
        raise FileNotFoundError(
            f"Expected PyInstaller output not found: {executable}"
        )

    LOGGER.info("PyInstaller build succeeded: %s", executable)


# ---------------------------------------------------------------------------
# Step 3 — Generate Inno Setup script
# ---------------------------------------------------------------------------


def generate_inno_script() -> Path:
    """Write installer_config.iss with dynamically resolved absolute paths."""
    LOGGER.info("Step 3/5 — Generating Inno Setup script")

    source_dir = (ROOT_DIR / "dist" / APP_NAME).resolve()
    output_dir = (ROOT_DIR / "dist").resolve()

    if not source_dir.is_dir():
        raise FileNotFoundError(f"PyInstaller bundle missing: {source_dir}")

    iss_content = f"""; Auto-generated by build_pipeline.py — do not edit manually.

#define MyAppName "{APP_NAME}"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Host Storage Service"
#define MyAppExeName "{APP_NAME}.exe"

[Setup]
AppId={INNO_APP_ID}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
DefaultDirName={{localappdata}}\\Programs\\{APP_NAME}
DefaultGroupName={{#MyAppName}}
PrivilegesRequired=lowest
OutputDir={_inno_path(output_dir)}
OutputBaseFilename={INSTALLER_BASENAME}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
DisableProgramGroupPage=yes
UninstallDisplayIcon={{app}}\\{{#MyAppExeName}}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked

[Files]
Source: "{_inno_path(source_dir)}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{autoprograms}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent
"""

    INSTALLER_SCRIPT.write_text(iss_content, encoding="utf-8")
    LOGGER.info("Inno Setup script written: %s", INSTALLER_SCRIPT)
    return INSTALLER_SCRIPT


def _inno_path(path: Path) -> str:
    """Convert a Windows path to an Inno Setup–safe string."""
    return str(path.resolve())


# ---------------------------------------------------------------------------
# Step 4 — Compile installer with ISCC
# ---------------------------------------------------------------------------


def locate_iscc() -> Path:
    """Find the Inno Setup compiler executable on this machine."""
    for candidate in ISCC_CANDIDATES:
        if candidate.is_file():
            LOGGER.info("Found Inno Setup compiler: %s", candidate)
            return candidate

    searched = "\n  - ".join(str(path) for path in ISCC_CANDIDATES)
    raise FileNotFoundError(
        "Inno Setup 6 compiler (ISCC.exe) was not found.\n"
        f"Searched:\n  - {searched}\n\n"
        "Install Inno Setup 6 from https://jrsoftware.org/isinfo.php "
        "and run this pipeline again."
    )


def compile_installer(iss_path: Path) -> Path:
    """Invoke ISCC.exe to produce the final setup executable."""
    LOGGER.info("Step 4/5 — Compiling installer with Inno Setup")

    iscc = locate_iscc()
    command = [str(iscc), str(iss_path.resolve())]

    return_code = _stream_subprocess(command, cwd=ROOT_DIR)
    if return_code != 0:
        raise RuntimeError(f"Inno Setup compiler failed with exit code {return_code}")

    installer_exe = ROOT_DIR / "dist" / f"{INSTALLER_BASENAME}.exe"
    if not installer_exe.is_file():
        raise FileNotFoundError(f"Expected installer not found: {installer_exe}")

    LOGGER.info("Installer compiled successfully: %s", installer_exe)
    return installer_exe


# ---------------------------------------------------------------------------
# Step 5 — Post-build cleanup
# ---------------------------------------------------------------------------


def post_build_cleanup() -> None:
    """Remove temporary build artifacts while keeping distributable outputs."""
    LOGGER.info("Step 5/5 — Post-build cleanup")

    if INSTALLER_SCRIPT.is_file():
        LOGGER.info("Removing temporary file: %s", INSTALLER_SCRIPT)
        INSTALLER_SCRIPT.unlink()

    build_dir = ROOT_DIR / "build"
    if build_dir.is_dir():
        LOGGER.info("Removing directory: %s", build_dir)
        shutil.rmtree(build_dir)

    generated_spec = ROOT_DIR / f"{APP_NAME}.spec"
    if generated_spec.is_file():
        LOGGER.info("Removing generated spec: %s", generated_spec)
        generated_spec.unlink()

    LOGGER.info("Post-build cleanup complete")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _stream_subprocess(command: list[str], *, cwd: Path) -> int:
    """Run a subprocess and stream combined stdout/stderr to the console."""
    LOGGER.debug("Working directory: %s", cwd)

    try:
        process = subprocess.Popen(
            command,
            cwd=str(cwd),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(
            f"Failed to start process: {' '.join(command)}"
        ) from exc

    assert process.stdout is not None
    for line in process.stdout:
        print(line, end="")

    return process.wait()


def _ensure_windows() -> None:
    if sys.platform != "win32":
        raise OSError(
            "This build pipeline targets Windows (PyInstaller + Inno Setup). "
            f"Current platform: {sys.platform}"
        )


def _ensure_pyinstaller_available() -> None:
    try:
        subprocess.run(
            [sys.executable, "-m", "PyInstaller", "--version"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        raise RuntimeError(
            "PyInstaller is not installed. Install it with:\n"
            "    pip install pyinstaller"
        ) from exc


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    """Execute the full build pipeline."""
    configure_logging()
    LOGGER.info("Starting HostStorageService production build pipeline")
    LOGGER.info("Project root: %s", ROOT_DIR)

    try:
        _ensure_windows()
        _ensure_pyinstaller_available()

        clean_old_artifacts()
        run_pyinstaller()
        iss_path = generate_inno_script()

        installer_path: Path | None = None
        try:
            installer_path = compile_installer(iss_path)
        except FileNotFoundError:
            LOGGER.warning(
                "Inno Setup not found. Skipping installer creation. "
                "Standalone production build in dist/ is ready!"
            )

        post_build_cleanup()

        LOGGER.info("=" * 60)
        LOGGER.info("BUILD SUCCESSFUL")
        LOGGER.info("Application bundle : %s", ROOT_DIR / "dist" / APP_NAME)
        if installer_path is not None:
            LOGGER.info("Installer package  : %s", installer_path)
        LOGGER.info("=" * 60)
        return 0

    except Exception:
        LOGGER.exception("Build pipeline failed")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
